apiVersion: v1
kind: Pod
metadata:
  name: oom
  labels:
    app.kubernetes.io/name: oom
spec:
  containers:
  - name: oom
    image: polinux/stress
    command: ["stress"]
    args: ["--vm","1","--vm-bytes","200M", "--vm-hang", "1"]
    resources:
      limits:
        memory: "100Mi"
