apiVersion: v1
kind: Pod
metadata:
  name: pending-pod
  labels:
    app.kubernetes.io/name: pending-pod
spec:
  containers:
  - name: pending-pod
    image: nginx/latest
    resources:
      requests:
        memory: "128Gi"
        cpu: "100"
