apiVersion: v1
kind: Pod
metadata:
  name: rediness
  labels:
    app.kubernetes.io/name: rediness
spec:
  containers:
  - name: rediness
    image: nginx:latest
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 3
