apiVersion: v1
kind: Pod
metadata:
  name: startup
  labels:
    app.kubernetes.io/name: startup
spec:
  containers:
  - name: startup
    image: busybox
    command:
      - /bin/sh
      - -c
      - >
        sleep 20;
        touch /tmp/started;
        sleep 600
    startupProbe:
      exec:
        command:
          - cat
          - /tmp/started
      periodSeconds: 5
      failureThreshold: 12
    livenessProbe:
      exec:
        command:
          - cat
          - /tmp/started
      periodSeconds: 5
      failureThreshold: 3
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "250m"
        memory: "256Mi"
