name: Deploy To Server

on:
    workflow_call:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v6
          
            - name: SSH to prod server && create app folder
              uses: appleboy/ssh-action@v1
              with: 
                host: ${{ secrets.EC2_SSH_HOST }}
                username: ${{ secrets.EC2_SSH_USERNAME }}
                key: ${{ secrets.EC2_SSH_KEY }}
                script: |
                    echo "Starting Deployment"
                    mkdir -p devops
            
            - name: Copy the docker-compose file to the server
              uses: appleboy/scp-action@v1
              with:
                host: ${{ secrets.EC2_SSH_HOST }}
                username: ${{ secrets.EC2_SSH_USERNAME }}
                key: ${{ secrets.EC2_SSH_KEY }}
                source: node/docker-compose.yml
                target: ~/devops
                strip_components: 1

            - name: Deploy to server
              uses: appleboy/ssh-action@v1
              with: 
                host: ${{ secrets.EC2_SSH_HOST }}
                username: ${{ secrets.EC2_SSH_USERNAME }}
                key: ${{ secrets.EC2_SSH_KEY }}
                script: |
                    echo "Logging into Docker Hub"
                    docker login -u ${{vars.DOCKERHUB_USERNAME}} -p ${{ secrets.DOCKERHUB_TOKEN}}
                    export DOCKERHUB_USERNAME=${{ vars.DOCKERHUB_USERNAME }}
                    export DOCKERHUB_IMAGE_TAG=${{ github.sha }}
                    echo "Running app"
                    cd devops && \
                    docker compose pull && \
                    docker compose up -d \
                    --build --force-recreate && \
                    docker image prune -f

