name: Deploy node app

on:
  workflow_run:
      workflows: ["Docker Build and Push"]
      types: [completed]
      branches: [main]

jobs:
  Deploy:
      if: github.event.workflow_run.conclusion == 'success'
      env:
        DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
        DOCKER_TAG: ${{ github.event.workflow.run_head_sha }}
      
      runs-on: self-hosted

      steps:
        - name: checkout code
          uses: actions/checkout@v4

        - name: deploy using docker compose
          run: docker compose down && docker compose up -d --build --force-recreate --pull always
