name: DevSecOps Pipeline

on:
    push:
        branches: [ main ]
    workflow_dispatch:

jobs:
    #CI (Continuous Integration with Security scanning)
    code-quality:
        uses: ./.github/workflows/code-quality.yml
        secrets: inherit

    secrets-scan:
        uses: ./.github/workflows/secrets-scan.yml
        secrets: inherit

    dependency-scan:
        uses: ./.github/workflows/dependency-scan.yml
        secrets: inherit

    docker-scan:
        uses: ./.github/workflows/docker-lint.yml
        secrets: inherit

    # Build and Push Docker Image
    docker-build:
        needs: [ code-quality, secrets-scan, dependency-scan, docker-scan ]
        uses: ./.github/workflows/docker-build-push.yml
        secrets: inherit

    # Image Security Scanning
    image-scan:
        needs: [ docker-build ]
        uses: ./.github/workflows/image-scan.yml
        secrets: inherit

    # CD (Continuous Deployment)
    deploy:
        needs: [ image-scan ]
        uses: ./.github/workflows/deploy-to-server.yml
        secrets: inherit
        