# Scan the Dockerfile for issues and CVEs
name: Docker lint

on:
    workflow_call:

jobs:
    validate-dockerfile:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v6

            - name: Docker linting
              uses: hadolint/hadolint-action@v3.1.0
              with:
                context: ./node
                dockerfile: ./node/Dockerfile