# Uses Trivy Image scanner for CVEs
name: Image Scanner

on:
    workflow_call:

jobs:
    image-scanner:
        runs-on: ubuntu-latest

        steps:
            
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN}}

            # Fail pipeline only if CRITICAL vulnerabilities exist
            - name: Trivy Scanner
              uses: aquasecurity/trivy-action@0.35.0
              with:
                image-ref: 'docker.io/${{ vars.DOCKERHUB_USERNAME }}/node-app:latest'
                severity: 'CRITICAL'
                exit-code: '1'

            # Report HIGH vulnerabilities but don't fail
            - name: Trivy Scan (Report HIGH)
              uses: aquasecurity/trivy-action@0.35.0
              with:
                image-ref: docker.io/${{ vars.DOCKERHUB_USERNAME }}/node-app:latest
                severity: HIGH
                exit-code: 0
