name: Manual Hello Workflow

on:
    workflow_dispatch:

jobs:
    manual-jobs:
        runs-on: ubuntu-latest
        
        steps:
              - name: Say Hello
                run: echo "Hello! This workflow was triggered manually."

              - name: Show User
                run: echo "Triggered by $GITHUB_ACTOR"

              - name: Show Date
                run: date