name: Secrets Scan

on:
  workflow_call:

jobs:
  secrets-Scan:
      runs-on: ubuntu-latest
      steps:
        - name: checkout code
          uses: actions/checkout@v6
          with:
            fetch-depth: 0

        - name: Run Gitleak Scanner
          uses: gitleaks/gitleaks-action@v2
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} #github actions manages it

